spring:
  security:
    user:
      name: yer
      password: galem
  datasource:
    url: jdbc:h2:mem:testdb # URL ??? H2 ? ??????????? ??????
    driverClassName: org.h2.Driver
    username: sa # ??? ???????????? ?? ?????????
    password:  # ?????? ?? ?????????
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop # ????????????? ?????????/??????? ?????
  h2:
    console:
      enabled: true # ???????? ??????? H2
      path: /h2-console # ???? ? ??????? H2
      settings:
        web-allow-others: true # ????????? ?????? ?? ?????? ?????? (??? ??????????)

